Added name key for the steps

diff --git a/.github/workflows/01-Building-Blocks.yml b/.github/workflows/01-Building-Blocks.yml
--- a/.github/workflows/01-Building-Blocks.yml
+++ b/.github/workflows/01-Building-Blocks.yml
@@ -5,20 +5,17 @@ jobs:
     name: First Job
     runs-on: macos-14
     steps:
-      - name:
-          Successful Job:
-            run: echo "Hello World!"
+      - name: Echo Hello World
+        run: echo "Hello World!"
   My-Second-Job:
     name: Second Job
     needs:
       - My-First-Job
     runs-on: ubuntu-latest
     steps:
-      - name:
-          Failed step:
-            run: |
-              - echo "I will fail"
-              - exit 1
-      - name:
-          Say Goodbye:
-            run: echo "I will pass"
+      - name: Echo Fail
+        run: |
+           echo "I will fail"
+           exit 1
+      - name: Echo Pass
+        run: echo "I will pass"
